import { createServerSideHelpers } from '@trpc/react-query/server';
import Head from 'next/head';
import { useMemo } from 'react';
import SuperJSON from 'superjson';

import { Header } from '@/components/header';
import { HostelList } from '@/components/hostel-list';
import { appRouter } from '@/server/api/root';
import { type OpeningMap } from '@/server/api/routers/openings';
import { db } from '@/server/db';
import { api } from '@/utils/api';

import styles from './index.module.css';

export async function getStaticProps() {
  const helpers = createServerSideHelpers({ router: appRouter, ctx: { db }, transformer: SuperJSON });

  await helpers.openings.getOpenings.prefetch();

  return {
    props: {
      trpcState: helpers.dehydrate(),
    },
  };
}

export default function Home() {
  const { data: openings } = api.openings.getOpenings.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <HostelList />
      </main>
    </>
  );
}
